<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9"> <![endif]-->
<!--[if !IE]><!--> <html lang="en"> <!--<![endif]-->
<head class="header-fixed header-fixed-space">
	<title>Blank Page | Unify - Responsive Website Template</title>

	<!-- Meta -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">


	<?php echo $this->headTitle('Tutor ')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
		->appendName('viewport', 'width=device-width, initial-scale=1.0')
		->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
	?>

	<!-- Le styles -->
<?php //echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
//		->prependStylesheet($this->basePath('css/style.css'))
//		->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
//		->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

	<!-- Scripts -->
	<?php // echo $this->headScript()
//		->prependFile($this->basePath('js/bootstrap.min.js'))
//		->prependFile($this->basePath('js/jquery.min.js'))
//		->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
//		->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
//	; ?>

	<!-- Favicon -->
<!--	<link rel="shortcut icon" href="favicon.ico">-->

	<!-- Web Fonts -->
<!--	<link rel='stylesheet' type='text/css' href='//fonts.googleapis.com/css?family=Open+Sans:400,300,600&amp;subset=cyrillic,latin'>-->

	<!-- CSS Global Compulsory -->
	<link rel="stylesheet" href="/assets1/plugins/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/assets1/css/style.css">

	<!-- CSS Header and Footer -->
	<link rel="stylesheet" href="/assets1/css/headers/header-v6.css">
	<link rel="stylesheet" href="/assets1/css/footers/footer-v5.css">

	<!-- CSS Implementing Plugins -->
<!--	<link rel="stylesheet" href="assets/plugins/animate.css">-->
<!--	<link rel="stylesheet" href="assets/plugins/line-icons/line-icons.css">-->
<!--	<link rel="stylesheet" href="assets/plugins/font-awesome/css/font-awesome.min.css">-->

	<!-- CSS Theme -->
<!--	<link rel="stylesheet" href="assets/css/theme-colors/default.css" id="style_color">-->

	<!-- CSS Customization -->
	<link rel="stylesheet" href="/assets1/css/custom.css">

	<!-- CSS Page Style -->
	<link rel="stylesheet" href="/assets1/css/pages/page_misc_sticky_footer.css">




</head>
<body class="header-fixed header-fixed-space">

	<div class="wrapper">
		<!--=== Header v6 ===-->
		<div class="header-v6 header-classic-white header-sticky">
			<!-- Navbar -->
			<div class="navbar mega-menu" role="navigation">
				<div class="container">
					<!-- Brand and toggle get grouped for better mobile display -->
					<div class="menu-container">
						<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- Navbar Brand -->
						<div class="navbar-brand">
							<a href="index.html">
								<img class="shrink-logo" src="assets/img/logo1-default.png" alt="Logo">
							</a>
						</div>
						<!-- ENd Navbar Brand -->
						<!-- Header Inner Right -->
						<div class="header-inner-right">
							<ul class="menu-icons-list">
								<li class="menu-icons shopping-cart">
									<i class="menu-icons-style radius-x fa fa-shopping-cart"></i>
									<span class="badge">0</span>
									<div class="shopping-cart-open">
										<span class="shc-title">No products in the Cart</span>
										<button type="button" class="btn-u"><i class="fa fa-shopping-cart"></i> Cart</button>
										<span class="shc-total">Total: <strong>$0.00</strong></span>
									</div>
								</li>
								<li class="menu-icons">
									<i class="menu-icons-style search search-close search-btn fa fa-search"></i>
									<div class="search-open">
										<input type="text" class="animated fadeIn form-control" placeholder="Start searching ...">
									</div>
								</li>
							</ul>
						</div>
						<!-- End Header Inner Right -->
					</div>
					<!-- Collect the nav links, forms, and other content for toggling -->
					<div class="collapse navbar-collapse navbar-responsive-collapse">
						<div class="menu-container">
							<?php echo $this->menuWidget(); ?>
						</div>
					</div><!--/navbar-collapse-->
				</div>
			</div>
			<!-- End Navbar -->
		</div>
		<!--=== End Header v6 ===-->

		<?php echo $this->content; ?>

		<!--=== Footer v5 ===-->
		<div id="footer-v5" class="footer-v5 sticky-footer">
			<div class="copyright">
				<div class="container">
					<ul class="list-inline terms-menu">
						<li class="silver">Copyright © 2014 - All Rights Reserved</li>
						<li><a href="#">Terms of Use</a></li>
						<li><a href="#">Privacy and Policy</a></li>
						<li><a href="#">License</a></li>
						<li><a href="#">Support</a></li>
					</ul>
				</div>
			</div>
		</div>
		<!--=== End Footer v5 ===-->
	</div>
	<?php echo $this->inlineScript() ?>

	<!-- JS Global Compulsory -->
	<!--<script type="text/javascript" src="assets/plugins/jquery/jquery.min.js"></script>-->
	<!--<script type="text/javascript" src="assets/plugins/jquery/jquery-migrate.min.js"></script>-->
	<!--<script type="text/javascript" src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>-->
	<!-- JS Implementing Plugins -->
	<!--<script type="text/javascript" src="assets/plugins/back-to-top.js"></script>-->
	<!--<script type="text/javascript" src="assets/plugins/smoothScroll.js"></script>-->
	<!-- JS Customization -->
	<!--<script type="text/javascript" src="assets/js/custom.js"></script>-->
	<!-- JS Page Level -->
	<!--<script type="text/javascript" src="assets/js/app.js"></script>-->
	<!--<script type="text/javascript" src="assets/js/plugins/style-switcher.js"></script>-->
	<!--<script type="text/javascript">-->
	<!--	jQuery(document).ready(function() {-->
	<!--		App.init();-->
	<!--		StyleSwitcher.initStyleSwitcher();-->
	<!--	});-->
	<!--</script>-->
	<!--[if lt IE 9]>
	<!--<script src="assets/plugins/respond.js"></script>-->
	<!--<script src="assets/plugins/html5shiv.js"></script>-->
	<!--<script src="assets/plugins/placeholder-IE-fixes.js"></script>-->
	<![endif]-->
</body>
</html>

