<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sTutor%s'), '<span class="zf-green">', '</span>') ?></h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p>Tutor</p>
            </div>
        </div>
    </div>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo $this->translate('Category') ?></h3>
			</div>
			<div class="panel-body">
				<select>
				<?php
					/** @var $child_category \MBase\Entity\Category */
					foreach ($recursive_category_iterator as $index => $child_category)
					{
						echo '<option value="' . $child_category->getId(). '">'
							. str_repeat('-&nbsp;', $recursive_category_iterator->getDepth())
							. $child_category->getTitle()
							. '</option>';

					}
				?>
				</select>
			</div>
		</div>
	</div>

	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo $this->translate('Menu') ?></h3>
			</div>
			<div class="panel-body">
				<select>
					<?php
					/** @var $child_menu \MBase\Entity\Menu */
					foreach ($recursive_menu_iterator as $index => $child_menu)
					{
						echo '<option value="' . $child_menu->getId(). '">'
							. str_repeat('-&nbsp;', $recursive_menu_iterator->getDepth())
							. $child_menu->getTitle()
							. '</option>';

					}
					?>
				</select>
			</div>
		</div>
	</div>
</div>
