<a class="btn btn-success" href="<?php echo $this->url('category/default', array('controller' => 'category', 'action' => 'add')); ?>">Создать</a>
<br>
<?php
if ($this->success)
	echo '<div class="alert alert-success">'.$this->success[0].'<button type="button" class="close" data-dismiss="alert">×</button></div>';

if ($this->error)
	echo '<div class="alert alert-danger">'.$this->error[0].'<button type="button" class="close" data-dismiss="alert">×</button></div>';
?>


<table class="table table-bordered table-striped table-hover table-condensed">
	<caption>Категории</caption>
	<thead>
	<tr>
		<th>ID</th>
		<th>Название</th>
		<th>Действие</th>
	</tr>
	</thead>
	<tbody>
	<?php
	/**
	 * @var $entity \Categoria\Entity\Category
	 */
	?>
	<?php if ($this->data): ?>
		<?php foreach( $this->data as $entity): ?>
			<tr>
				<td><?php echo $entity->getId(); ?></td>
				<td><?php echo $entity->getName(); ?></td>
				<td>
					<a class="btn btn-success" href="<?php echo $this->url('category/default', array('controller' => 'category', 'action' => 'edit', 'id' => $entity->getId())); ?>"><i class="glyphicon glyphicon-pencil"></i> </a>
					<a class="btn btn-danger" href="<?php echo $this->url('category/default', array('controller' => 'category', 'action' => 'delete', 'id' => $entity->getId())); ?>"><i class="glyphicon glyphicon-remove-sign"></i> </a>
				</td>
			</tr>
		<?php endforeach; ?>
	<?php else: ?>
		<p>Не найдено ни одной записи!</p>
	<?php endif; ?>


	</tbody>
</table>