<!DOCTYPE html>
<html>

	<head>

		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">

		<title>Blank</title>

		<link href="/assets/css/bootstrap.min.css" rel="stylesheet">
		<link href="/assets/font-awesome/css/font-awesome.css" rel="stylesheet">

		<link href="/assets/css/animate.css" rel="stylesheet">
		<link href="/assets/css/style.css" rel="stylesheet">

	</head>
	<body class="md-skin fixed-sidebar fixed-nav">
		<div id="wrapper">
			<nav class="navbar-default navbar-static-side" role="navigation">
				<div class="sidebar-collapse">
					<ul class="nav metismenu" id="side-menu">
						<li class="nav-header">
							<div class="dropdown profile-element">
								<a data-toggle="dropdown" class="dropdown-toggle" href="#">
		                            <span class="clear">
			                            <span class="block m-t-xs">
				                            <strong class="font-bold">Name</strong>
		                                </span>
			                            <span class="text-muted text-xs block">
				                            Director <b class="caret"></b>
			                            </span>
		                            </span>
								</a>
								<ul class="dropdown-menu animated fadeInRight m-t-xs">
									<li><a href="">Profile</a></li>
									<li class="divider"></li>
									<li><a href="">Logout</a></li>
								</ul>
							</div>
							<div class="logo-element">
								MS
							</div>
						</li>
						<li class="active">
							<a href="/">
								<i class="fa fa-th-large"></i>
								<span class="nav-label">Main view</span>
							</a>
						</li>
						<li class="active">
							<a href="/application/index/form">
								<i class="fa fa-th-large"></i>
								<span class="nav-label">Form</span>
							</a>
						</li>
						<li class="active">
							<a href="/application/index/test">
								<i class="fa fa-th-large"></i>
								<span class="nav-label">Test</span>
							</a>
						</li>

						<li>
							<a href="">
								<i class="fa fa-th-large"></i>
								<span class="nav-label">Materials</span>
							</a>
						</li>
						<li>
							<a href="#">
								<i class="fa fa-th-large"></i>
								<span class="nav-label">Menu</span>

							</a>
							<ul class="nav nav-second-level collapse">
								<li><a href="">Created</a></li>
								<li><a href="">Created</a></li>
								<li><a href="">Created</a></li>
								<li><a href="">Created</a></li>
							</ul>
						</li>
					</ul>
				</div>
			</nav>

			<div id="page-wrapper" class="gray-bg">
				<div class="row border-bottom">
					<nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
						<div class="navbar-header">
							<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
							<form role="search" class="navbar-form-custom" method="post" action="#">
								<div class="form-group">
									<input type="text" placeholder="Search for something..." class="form-control" name="top-search" id="top-search">
								</div>
							</form>
						</div>
						<ul class="nav navbar-top-links navbar-right">
							<li>
								<a href="#">
									<i class="fa fa-sign-out"></i> Log out
								</a>
							</li>
						</ul>

					</nav>
				</div>
				<div class="wrapper wrapper-content"> <!--  animated fadeInRight -->
					<div class="row">
						<div class="col-lg-12">
							<div class="text-center m-t-lg">
								<?php echo $this->content; ?>
							</div>
						</div>
					</div>
				</div>
				<div class="footer">
					<div class="pull-right">

					</div>
					<div>
						<strong>Copyright</strong> Example Company &copy; 2016
					</div>
				</div>

			</div>
		</div>

		<!-- Mainly scripts -->
		<script src="/assets/js/jquery-2.1.1.js"></script>
		<script src="/assets/js/bootstrap.min.js"></script>
		<script src="/assets/js/plugins/metisMenu/jquery.metisMenu.js"></script>
		<script src="/assets/js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

		<!-- Custom and plugin javascript -->
		<script src="/assets/js/inspinia.js"></script>
		<script src="/assets/js/plugins/pace/pace.min.js"></script>

	</body>
</html>
