<nav class="navbar-default navbar-static-side" role="navigation">
	<div class="sidebar-collapse">
		<ul class="nav metismenu" id="side-menu">
			<li class="nav-header">
				<div class="dropdown profile-element">
					<a data-toggle="dropdown" class="dropdown-toggle" href="#">
		                            <span class="clear">
			                            <span class="block m-t-xs">
				                            <strong class="font-bold">Name</strong>
		                                </span>
			                            <span class="text-muted text-xs block">
				                            Director <b class="caret"></b>
			                            </span>
		                            </span>
					</a>
					<ul class="dropdown-menu animated fadeInRight m-t-xs">
						<li><a href="">Profile</a></li>
						<li class="divider"></li>
						<li><a href="">Logout</a></li>
					</ul>
				</div>
				<div class="logo-element">
					MS
				</div>
			</li>
			<li class="active">
				<a href="/">
					<i class="fa fa-th-large"></i>
					<span class="nav-label">Main view</span>
				</a>
			</li>
			<li>
				<a href="/application/index/form">
					<i class="fa fa-th-large"></i>
					<span class="nav-label">Form</span>
				</a>
			</li>
			<li>
				<a href="/application/index/test">
					<i class="fa fa-th-large"></i>
					<span class="nav-label">Test</span>
				</a>
			</li>

			<li class="active">
				<a href="">
					<i class="fa fa-th-large"></i>
					<span class="nav-label">Materials</span>
				</a>
				<ul class="nav nav-second-level collapse">
					<li><a href="/application/index/form-material">Form Material</a></li>
					<li><a href="/application/index/view-material">View Material</a></li>
				</ul>
			</li>
			<li class="active">
				<a href="">
					<i class="fa fa-th-large"></i>
					<span class="nav-label">Category</span>
				</a>
				<ul class="nav nav-second-level collapse">
					<li><a href="/application/index/form-category">Form Category</a></li>
					<li><a href="/application/index/view-category">View Category</a></li>
				</ul>
			</li>
			<li class="active">
				<a href="#">
					<i class="fa fa-th-large"></i>
					<span class="nav-label">Menu</span>
				</a>
				<ul class="nav nav-second-level collapse">
					<li><a href="/application/index/form-menu-type">Form Menu Type</a></li>
					<li><a href="/application/index/form-menu">Form Menu</a></li>
					<li><a href="/application/index/view-menu">View Menu</a></li>
					<li><a href="/application/index/view-menu-type">View Menu Type</a></li>
				</ul>
			</li>
		</ul>
	</div>
</nav>