
<div class="container content">
	<div class="row">
		<div class="col-md-3"></div>
		<!-- Begin Content -->
		<div class="col-md-9">
			<div class="content">
				<div>

				<?php



					$form = $this->menuForm;
					//\Zend\Debug\Debug::dump($form);die;
					$form->prepare();
					//$form->setAttribute('action', '/app'); // чтобы использовать как виджет из любых страниц
					$form->setAttribute('method', 'post');
					$form->setAttribute('autocomplete', 'off');


				echo $this->form()->openTag($form) ?>




<!--					<form action="#" class="sky-form">-->

						<header>Success states for elements</header>
						Название
						<fieldset>
							<section>
								<label class="label"><?php echo $this->formLabel($form->get('title')); ?></label>
								<label class="input state-success">
									<?php echo $this->formText($form->get('title')); ?>
								</label>
								<?php if (count($form->get('title')->getMessages())): ?>
									<div class="note note-success"><?php echo $this->formElementErrors($form->get('title')); ?></div>
								<?php endif ?>
							</section>
						</fieldset>
						<fieldset>
							<section>
								<label class="label"><?php echo $this->formLabel($form->get('alias')); ?></label>
								<label class="input state-success">
									<?php echo $this->formText($form->get('alias')); ?>
								</label>
								<?php if (count($form->get('alias')->getMessages())): ?>
									<div class="note note-success"><?php echo $this->formElementErrors($form->get('alias')); ?></div>
								<?php endif ?>
							</section>
						</fieldset>
						<fieldset>
							<section>
								<label class="label"><?php echo $this->formLabel($form->get('description')); ?></label>
								<label class="textarea state-success">
									<?php echo $this->formTextarea($form->get('description')); ?>
								</label>
								<?php if (count($form->get('description')->getMessages())): ?>
									<div class="note note-success"><?php echo $this->formElementErrors($form->get('description')); ?></div>
								<?php endif ?>
							</section>
						</fieldset>

						<fieldset>
							<section>
								<label class="label"><?php echo $this->formLabel($form->get('keyword')); ?></label>
								<label class="input state-success">
									<?php echo $this->formText($form->get('keyword')); ?>
								</label>
								<?php if (count($form->get('keyword')->getMessages())): ?>
									<div class="note note-success"><?php echo $this->formElementErrors($form->get('keyword')); ?></div>
								<?php endif ?>
							</section>
						</fieldset>
						<fieldset>
							<section>
								<label class="label"><?php echo $this->formLabel($form->get('introtext')); ?></label>
								<label class="textarea state-success">
									<?php echo $this->formTextarea($form->get('introtext')); ?>
								</label>
								<?php if (count($form->get('introtext')->getMessages())): ?>
									<div class="note note-success"><?php echo $this->formElementErrors($form->get('introtext')); ?></div>
								<?php endif ?>
							</section>
						</fieldset>
						<fieldset>
							<section>
								<label class="label"><?php echo $this->formLabel($form->get('fulltext')); ?></label>
								<label class="textarea state-success">
									<?php echo $this->formTextarea($form->get('fulltext')); ?>
								</label>
								<?php if (count($form->get('fulltext')->getMessages())): ?>
									<div class="note note-success"><?php echo $this->formElementErrors($form->get('fulltext')); ?></div>
								<?php endif ?>
							</section>
						</fieldset>
						<fieldset>
							<section>
								<label class="label"><?php echo $this->formLabel($form->get('params')); ?></label>
								<label class="textarea state-success">
									<?php echo $this->formTextarea($form->get('params')); ?>
								</label>
								<?php if (count($form->get('params')->getMessages())): ?>
									<div class="note note-success"><?php echo $this->formElementErrors($form->get('params')); ?></div>
								<?php endif ?>
							</section>
						</fieldset>
						<fieldset>
							<section>
								<label class="label"><?php echo $this->formLabel($form->get('categoryId')); ?></label>
								<label class="select state-success">
									<?php echo $this->formSelect($form->get('categoryId')); ?>
									<i></i>
								</label>
								<div class="note note-success">Thanks for your selection.</div>
							</section>
						</fieldset>

						<?= $this->formButton($form->get('submit')) ?>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>


<?php
//
//echo $this->form()->openTag($form) ?>
<!--<dl class="zend_form">-->
<!--	--><?php //foreach ($form as $element): ?>
<!--		--><?php //if ($element->getLabel() != null && !$element instanceof Zend\Form\Element\Button): ?>
<!--			<dt>--><?php //echo $this->formLabel($element) ?><!--</dt>-->
<!--		--><?php //endif ?>
<!--		<dd>--><?php //echo $this->formElement($element) . $this->formElementErrors($element) ?><!--</dd>-->
<!--	--><?php //endforeach ?>
<!--</dl>-->
<?php //if ($this->redirect): ?>
<!--	<input type="hidden" name="redirect" value="--><?php //echo $this->redirect ?><!--">-->
<?php //endif ?>
<?php //echo $this->form()->closeTag() ?>
