<nav class="navbar navbar inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="collapse navbar-collapse">
			<ul class="nav navbar-nav">
				<?php foreach ($menuIterator as $menu): ?>
					<li class="active">
							<a href="<?php echo $menu->getPath(); ?>">
								<?php echo $menu->getTitle(); ?>
							</a>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
</nav>