<?php
/** @var $content \MBase\Entity\Content */

?>
<div class="jumbotron">
	<h1><?php echo sprintf($this->translate($content->getTitle()), '<span class="zf-green">', '</span>') ?></h1>
</div>

<div class="row">

	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h3 class="panel-title"><?php echo $this->translate($content->getCategory()->getTitle()) ?></h3>
			</div>
			<div class="panel-body">
				<p><?php echo $this->translate($content->getFullText()) ?></p>
			</div>
		</div>
	</div>
</div>