<div class="jumbotron">
    <h1><?php echo sprintf($this->translate('Welcome to %sTutor%s'), '<span class="zf-green">', '</span>') ?></h1>
</div>

<div class="row">

    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
            </div>
            <div class="panel-body">
                <p>FORM</p>
            </div>
        </div>
    </div>
</div>
