<div class="col-lg-10">
	<div class="ibox float-e-margins">
		<div class="ibox-title">
			<h5>Menu</h5>
		</div>
		<div class="ibox-content" style="display: block;">
			<form method="post" class="form-horizontal">
				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Тип пункта меню <span style="color:red;">*</span>:</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" name="type">
					</div>
					<div class="col-sm-4">
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Заголовок <span style="color:red;">*</span>:</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" name="title">
					</div>
					<div class="col-sm-4">
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Алиас :</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" name="alias">
					</div>
					<div class="col-sm-4">
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Ссылка :</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" name="link">
					</div>
					<div class="col-sm-4">
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Состояние :</label>
					<div class="col-sm-6">
						<select class="form-control m-b" name="state">
							<option value="1">Опубликовано</option>
							<option value="2">Не опубликовано</option>
						</select>
					</div>
					<div class="col-sm-4">
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Тип меню :</label>
					<div class="col-sm-6">
						<select class="form-control m-b" name="menutype">
							<option value="menu_1">Меню 1</option>
							<option value="menu_2">Меню 2</option>
							<option value="menu_3">Меню 3</option>
							<option value="menu_4">Меню 4</option>
						</select>
					</div>
					<div class="col-sm-4">
					</div>
				</div>
				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Родительский элемент :</label>
					<div class="col-sm-6">
						<select class="form-control m-b" name="parentId">
							<option value="menu_element_1">menu_element 1</option>
							<option value="menu_element_2">menu_element 2</option>
							<option value="menu_element_3">menu_element 3</option>
							<option value="menu_element_4">menu_element 4</option>
						</select>
					</div>
					<div class="col-sm-4">
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Главная страница :</label>
					<div class="col-sm-10 text-left">
						<label>
							<input type="radio" checked="" value="1" name="home">
							Да
						</label>&nbsp;
						<label>
							<input type="radio" value="0" name="home">
							Нет
						</label>
					</div>

				</div>
				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-lg-2 control-label">ID :</label>
					<div class="col-lg-10">
						<p class="form-control-static text-left">0</p>
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<div class="col-sm-4 col-sm-offset-2">
						<button class="btn btn-primary" type="submit">Создать</button>
					</div>
				</div>

			</form>
		</div>
	</div>
</div>
