<div class="col-lg-8">
<div class="ibox float-e-margins">
<div class="ibox-title">
	<h5>Title form <small>descrition.</small></h5>
</div>
<div class="ibox-content" style="display: block;">
<form method="get" class="form-horizontal">
</form>
</div>
</div>
</div>





<div class="col-lg-8">
	<div class="ibox float-e-margins">
		<div class="ibox-title">
			<h5>Title form <small>descrition.</small></h5>
		</div>
		<div class="ibox-content" style="display: block;">
			<form method="get" class="form-horizontal">

				<div class="form-group">
					<label class="col-sm-2 control-label">Normal</label>
					<div class="col-sm-10">
						<input type="text" class="form-control">
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Help text</label>
					<div class="col-sm-10">
						<input type="text" class="form-control">
						<span class="help-block m-b-none">Description actions.</span>
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Password</label>
					<div class="col-sm-10">
						<input type="password" class="form-control" name="password">
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Placeholder</label>
					<div class="col-sm-10">
						<input type="text" placeholder="placeholder" class="form-control">
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-lg-2 control-label">Disabled</label>
					<div class="col-lg-10">
						<input type="text" disabled="" placeholder="Disabled input here..." class="form-control">
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-lg-2 control-label">Static control</label>
					<div class="col-lg-10">
						<p class="form-control-static">email@example.com</p>
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Checkboxes and radios <br>
						<small class="text-navy">Normal Bootstrap elements</small>
					</label>
					<div class="col-sm-10">
						<div>
							<label>
								<input type="checkbox" value="">
								Option one is this and that—be sure to include why it's great
							</label>
						</div>
						<div>
							<label>
								<input type="radio" checked="" value="option1" id="optionsRadios1" name="optionsRadios">
								Option one is this and that—be sure to include why it's great
							</label>
						</div>
						<div>
							<label>
								<input type="radio" value="option2" id="optionsRadios2" name="optionsRadios">
								Option two can be something else and selecting it will deselect option one
							</label>
						</div>
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Inline checkboxes</label>
					<div class="col-sm-10">
						<label class="checkbox-inline"><input type="checkbox" value="option1" id="inlineCheckbox1"> a </label>
						<label class="checkbox-inline"><input type="checkbox" value="option2" id="inlineCheckbox2"> b </label>
						<label class="checkbox-inline"><input type="checkbox" value="option3" id="inlineCheckbox3"> c </label>
					</div>
				</div>
				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Inline checkboxes</label>
					<div class="col-sm-10"><label class="checkbox-inline i-checks">
							<div class="icheckbox_square-green" style="position: relative;">
								<input type="checkbox" value="option1" style="position: absolute; opacity: 0;">
								<ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background-color: rgb(255, 255, 255); border: 0px; opacity: 0; background-position: initial initial; background-repeat: initial initial;"></ins>
							</div>
							a
						</label>
						<label class="checkbox-inline i-checks">
							<div class="icheckbox_square-green" style="position: relative;">
								<input type="checkbox" value="option2" style="position: absolute; opacity: 0;">
								<ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background-color: rgb(255, 255, 255); border: 0px; opacity: 0; background-position: initial initial; background-repeat: initial initial;"></ins>
							</div>
							b
						</label>
						<label class="checkbox-inline i-checks">
							<div class="icheckbox_square-green" style="position: relative;">
								<input type="checkbox" value="option3" style="position: absolute; opacity: 0;">
								<ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background-color: rgb(255, 255, 255); border: 0px; opacity: 0; background-position: initial initial; background-repeat: initial initial;"></ins>
							</div>
							c
						</label>
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Select</label>
					<div class="col-sm-10">
						<select class="form-control m-b" name="account">
							<option>option 1</option>
							<option>option 2</option>
							<option>option 3</option>
							<option>option 4</option>
						</select>
						<div class="col-lg-4 m-l-n">
							<select class="form-control" multiple="">
								<option>option 1</option>
								<option>option 2</option>
								<option>option 3</option>
								<option>option 4</option>
							</select>
						</div>
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Column sizing</label>
					<div class="col-sm-10">
						<div class="row">
							<div class="col-md-2">
								<input type="text" placeholder=".col-md-2" class="form-control">
							</div>
							<div class="col-md-3">
								<input type="text" placeholder=".col-md-3" class="form-control">
							</div>
							<div class="col-md-4">
								<input type="text" placeholder=".col-md-4" class="form-control">
							</div>
						</div>
					</div>
				</div>

				<div class="hr-line-dashed"></div>

				<div class="form-group">
					<label class="col-sm-2 control-label">Segmented</label>
					<div class="col-sm-10">
						<div class="input-group">
							<input type="text" class="form-control">
							<div class="input-group-btn">
								<button tabindex="-1" class="btn btn-white" type="button">Action</button>
								<button data-toggle="dropdown" class="btn btn-white dropdown-toggle" type="button">
									<span class="caret"></span>
								</button>
								<ul class="dropdown-menu pull-right">
									<li><a href="#">Action</a></li>
									<li><a href="#">Another action</a></li>
									<li><a href="#">Something else here</a></li>
									<li class="divider"></li>
									<li><a href="#">Separated link</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="hr-line-dashed"></div>
				<div class="form-group">
					<div class="col-sm-4 col-sm-offset-2">
						<button class="btn btn-white" type="submit">Cancel</button>
						<button class="btn btn-primary" type="submit">Save changes</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>