<div class="row">
	<div class="col-lg-6">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>Все меню</h5>
				<div class="ibox-tools">

				</div>
			</div>
			<div class="ibox-content">

				<table class="table table-bordered">
					<thead>
						<tr>
							<th class="text-center">#</th>
							<th class="text-center">Заголовок</th>
							<th class="text-center">Тип</th>
							<th class="text-center">Опубликовано</th>
							<th class="text-center">Действия</th>
						</tr>
					</thead>
					<tbody>
					<?php if (!empty($menuTypes)): ?>
						<?php foreach ($menuTypes as $menu):?>
							<tr>
								<td><?php echo $menu['id']; ?></td>
								<td><?php echo $menu['title']; ?></td>
								<td><?php echo $menu['type']; ?></td>
								<td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
								<td>
									<a href="#"><i class="fa fa-wrench text-navy"></i></a>
									&nbsp;|&nbsp;
									<a href="#"><i class="fa fa-times text-navy"></i></a>
								</td>
							</tr>
						<?php endforeach; ?>
					<?php else: ?>
						<tr>
							<td colspan="5">Пусто!</td>
						</tr>
					<?php endif; ?>
					</tbody>
				</table>
				<a href="/application/index/form-menu-type"><button type="button" class="btn btn-default btn-sm">Добавить меню</button></a>
			</div>
		</div>

	</div>
	<div class="col-lg-6">

	</div>
</div>