<div class="row">
	<div class="col-lg-6">
		<div class="ibox float-e-margins">
			<div class="ibox-title">
				<h5>Пункты меню</h5>
				<div class="ibox-tools">
				</div>
			</div>
			<div class="ibox-content">
				<table class="table table-bordered">
					<thead>
					<tr>
						<th class="text-center">#</th>
						<th class="text-center">Заголовок</th>
						<th class="text-center">Состояние</th>
						<th class="text-center">Порядок</th>
						<th class="text-center">Тип пункта</th>
						<th class="text-center">Главная</th>
						<th class="text-center">Действия</th>
					</tr>
					</thead>
					<tbody>
					<?php if (!empty($menuList)): ?>
						<?php foreach ($menuList as $menu):?>
							<tr>
								<td><?php echo $menu['id']; ?></td>
								<td><?php echo $menu['title']; ?></td>
								<td><i class="fa fa-check text-navy"></td>
								<td><?php echo $menu['order']; ?></td>
								<td><?php echo $menu['type']; ?></td>
								<td><a href="#"><i class="fa fa-check text-navy"></i></a></td>
								<td>
									<a href="#"><i class="fa fa-wrench text-navy"></i></a>
									&nbsp;|&nbsp;
									<a href="#"><i class="fa fa-times text-navy"></i></a>
								</td>
							</tr>
						<?php endforeach; ?>
					<?php else: ?>
						<tr>
							<td colspan="7">Пусто!</td>
						</tr>
					<?php endif; ?>
					</tbody>
				</table>
				<a href="/application/index/form-menu"><button type="button" class="btn btn-default btn-sm">Добавить пункт меню</button></a>
			</div>
		</div>

	</div>
	<div class="col-lg-6">

	</div>
</div>